'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Views

    Partial Public Class Painel

        '''<summary>
        '''linkCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkCategories As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkProducts As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkEntities control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkEntities As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkUsers As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkDav control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkDav As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkFinances control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkFinances As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkAgenda control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkAgenda As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkOR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkOR As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkReports As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkStore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkStore As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
