'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Views

    Partial Public Class Store

        '''<summary>
        '''linkAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkAddress As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkRegistration As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkPayConds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkPayConds As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkEstimate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkEstimate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkSMTP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkSMTP As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkStatuses control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkStatuses As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkWebsite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkWebsite As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''linkTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents linkTemplates As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
