
Namespace Components.Interfaces.Models

    Public Interface ISofter

        Property acrescimo As Single
        Property admissao As DateTime
        Property aliquotaicms As Double
        Property aliquotaipi As Double
        Property aliquotaiss As Decimal
        Property aplicacao As String
        Property atividadevendedor As Integer
        Property ativo As Boolean
        Property ax As String
        Property bairro As String
        Property bairropessoa As String
        Property bairrotrabalho As String
        Property barras As String
        Property bloqueado As Boolean
        Property bloqueiodefinitivo As Boolean
        Property bloquiodecredito As Boolean
        Property c_c_custofixo As Double
        Property c_c_freteper As Double
        Property c_c_impostfed As Double
        Property c_c_ipi As Double
        Property c_c_subtrib As Double
        Property cadastro As DateTime
        Property cadastroinicial As DateTime
        Property carencia As Integer
        Property cartao As Boolean
        Property categoria As Integer
        Property ccf As Integer
        Property cep As String
        Property ceppessoa As String
        Property ceptrabalho As String
        Property cfop_saida_estado As String
        Property cgccpf As String
        Property cidade As String
        Property cidadepessoa As String
        Property cidadetrabalho As String
        Property classe As Integer
        Property classificacao As Integer
        Property cobrarjuros As Boolean
        Property cod_barras As String
        Property cod_grupo_fiscal As String
        Property cod_trib_ecf As Integer
        Property codclasse As Integer
        Property codicli As Integer
        Property codconjuge As Integer
        Property codconvenio As String
        Property codigo As Integer
        Property codigoaliquotatrib As Integer
        Property codigofabricante As Integer
        Property codigofornecedor As Integer
        Property codigogrupo As Integer
        Property codigopessoa As Integer
        Property codigosubgrupo As Integer
        Property codpay As Integer
        Property codproduto As Integer
        Property codprofissao As Integer
        Property codregiao As Integer
        Property codiven As Integer
        Property codvendedor As Integer
        Property cofins As Decimal
        Property comentrada As Boolean
        Property comissao As Decimal
        Property complemento As String
        Property complementotrabalho As String
        Property composicao As Boolean
        Property condpag As Integer
        Property condpagnome As String
        Property contato As String
        Property contato2 As String
        Property convenio As Integer
        Property coo As Integer
        Property coo_vinculado As Integer
        Property cpf_cnpj As String
        'Property cro As Integer
        'Property crz As Integer
        Property csosn As String
        Property cst As String
        Property ctps As String
        Property cupomcancelado As Boolean
        Property custo_final As Single
        Property custo_liq As Single
        Property custobruto As Single
        Property custoliquido As Single
        Property customedio As Single
        Property data_alteracao As DateTime
        Property data_cadastro As DateTime
        Property datavenda As DateTime
        Property datacadastro As DateTime
        Property datanasfundacao As DateTime
        Property demissao As DateTime
        Property desativado As Boolean
        Property desc_compl As String
        Property desconto As Decimal
        Property descontoperc As Decimal
        Property descperc As Decimal
        Property descrevenda As Single
        Property descricao As String
        Property desp_acessorias As Double
        Property email As String
        Property embalagem As Double
        Property encargos As Double
        Property est_min As Decimal
        Property estado As String
        Property estadocivil As String
        Property estadopessoa As String
        Property estadotrabalho As String
        Property estoque As Decimal
        Property estoqueatual As Double
        Property estoquemaximo As Double
        Property estoqueminimo As Double
        Property fantasia As String
        Property fax As String
        Property filiacao As String
        Property flexivel As Boolean
        Property foneref1 As String
        Property foneref2 As String
        Property fornecedor As Integer
        Property fornecedores As String
        Property frete As Decimal
        Property garantia As Integer
        'Property gnf As Integer
        Property grupo As String
        Property grupofiscal As Integer
        Property homepage As String
        Property iat As String
        Property icms As Decimal
        Property incres As Integer
        Property ingredientes As String
        Property insc_municipal As String
        Property inscricaorg As String
        Property intervalo As Integer
        Property intervalo_dias As String
        Property ipi As Decimal
        Property ippt As String
        Property limitecredito As Single
        Property local_trabalho As String
        Property localizacao As String
        Property logradouro As String
        Property logradouropessoa As String
        Property logradourotrabalho As String
        Property lucro As Double
        Property nacionalidade As String
        Property naoimportarcustos As Boolean
        Property naoimportarestoque As Boolean
        Property nasccontato As DateTime
        Property nasccontato2 As DateTime
        Property nascimento As DateTime
        Property naturalidade As String
        Property natureza As String
        Property nbmsh As String
        Property ncm As String
        Property nfe_pmvast As Double
        Property nfe_predbc As Double
        Property nfe_predbcst As Double
        Property nome As String
        Property nompais As String
        Property nro_parcelas As Integer
        Property numdav As Integer
        Property numdoc As Integer
        Property numero As String
        Property numerotrabalho As String
        'Property numfab As String
        'Property nummaquina As String
        Property obs As String
        Property observacao As String
        Property opercard As Integer
        Property outrosacrescimos As Single
        Property outrosdescontos As Single
        Property padrao As Boolean
        Property pagarcomissao As Boolean
        Property peso As Decimal
        Property pesopadrao As Double
        Property pis As Decimal
        Property politica_comissao As Integer
        Property preco As Single
        Property primeira_compra As DateTime
        Property principal As Boolean
        Property produto As Integer
        Property produtomontado As Boolean
        Property quantidade As Double
        Property razao As String
        Property ref As String
        Property referencia As String
        Property referencia1 As String
        Property referencia2 As String
        Property refxml As String
        Property renda As Single
        Property responsavel As String
        Property revendaconsumidor As String
        Property rg_insc_est As String
        Property salario As Single
        Property sequenciadav As Integer
        Property seriais As Boolean
        Property sexo As String
        Property spc As Boolean
        Property status As Integer
        Property sub_trib As Decimal
        Property telefone As String
        Property telefone2 As String
        Property telefoneprincipal As String
        Property tipo As String
        Property tipo_logradouro As String
        Property tipologradouropessoa As String
        Property tipologradourotrabalho As String
        Property tipopessoa As Integer
        Property tipopessoafj As String
        Property tipoproduto As String
        Property total As Single
        Property ultima_compra As DateTime
        Property unidade As String
        Property unidadedivisora As Integer
        Property unidadeid As Integer
        Property usarendprincipal As Boolean
        Property validade As Integer
        Property valordin As Single
        Property valorunitario As Single
        Property vencimentos As Boolean
        Property vendedor As Integer
        Property vrcartao As Single
        Property vrchepre As Single
        Property vrchevis As Single
        Property vrconv As Single
        Property vrcred As Single
        Property vrvale As Single
        Property website As String
        Property ativobalanca As Boolean
    End Interface
End Namespace